name: CI Tests

on: [pull_request,push]

jobs:
  Ubuntu:
    runs-on: ubuntu-22.04
    name: Ubuntu
    env:
      QT_VERSION: 6.3.0

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/Qt
          key: ${{ runner.os }}-Qt-Cache-${{ env.QT_VERSION }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.QT_VERSION }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Install prerequisties
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            libglu1-mesa-dev \
            libxkbcommon-dev \
            libvulkan-dev \
            libgl2ps-dev

      - name: Configuring
        run: |
          mkdir build && cd build
          cmake .. \
            -DBUILD_SHARED_LIBS=ON

      - name: Building
        run: |
          make -j$(nproc) -C build

  MSVC:
    name: MSVC_Qt_${{ matrix.qt_version }}
    runs-on: windows-latest
    env:
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
    strategy:
      fail-fast: false
      matrix:
        qt_version: [5.15.2, 6.3.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/Qt
          key: ${{ runner.os }}-Qt-Cache-${{ matrix.qt_version }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_version }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Setup NuGet Credentials
        run: |
          & $(vcpkg fetch nuget | select -last 1) sources add `
          -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" `
          -name "GitHub" `
          -username ${{ github.repository_owner }} `
          -password "${{ secrets.GITHUB_TOKEN }}"

      - name: vcpkg package restore
        run: |
          vcpkg install gl2ps --triplet x64-windows

      - name: Configuring
        run: |
          mkdir build; cd build
          cmake .. `
            -DCMAKE_BUILD_TYPE=Release `
            -DBUILD_SHARED_LIBS=ON `
            -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake

      - name: Building
        run: |
          cmake --build build --config Release -- -maxCpuCount

  MinGW-w64:
    runs-on: windows-2022
    name: MSYS2 ${{ matrix.msystem }}
    strategy:
      fail-fast: false
      matrix:
        msystem: [UCRT64, CLANG64]
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install MinGW-w64 packages
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          release: false
          update: true
          pacboy: >-
            cmake:p
            ninja:p
            cc:p
            qt6-base:p
            gl2ps:p

      - name: Configuring
        run: |
          mkdir build && cd build
          cmake ..

      - name: Building
        run: |
          cmake --build build

  macos:
    runs-on: macos-12
    name: macos
    env:
      QT_VERSION: 6.3.0

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/Qt
          key: ${{ runner.os }}-Qt-Cache-${{ env.QT_VERSION }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.QT_VERSION }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Install prerequisties
        run: |
          brew install gl2ps

      - name: Configuring
        run: |
          mkdir build && cd build
          cmake .. \
            -DBUILD_SHARED_LIBS=ON

      - name: Building
        run: |
          make -j$(sysctl -n hw.logicalcpu) -C build
